### PR TITLE
Update to OS v3.2.1

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Companion PR: https://github.com/NREL/resstock/pull/661 (ServerDirectoryCleanup updates).

This PR is necessary to work with resstock develop.

By setting `skip_zip_results=True` in the workflow generator, each datapoint's `run` directory contains all simulation files and they aren't contained in a `data_point.zip`. Also, the size of `simulations_job0.tar.gz` actually decreases.

**BEFORE**
image

image

image

**AFTER**
image

image

## Checklist

Not all may apply

- [ ] Code changes (must work)
- [ ] Tests exercising your feature/bug fix (check coverage report on CircleCI build -> Artifacts)
- [ ] All other unit tests passing
- [ ] Update validation for project config yaml file changes
- [ ] Update existing documentation
- [ ] Run a small batch run to make sure it all works (local is fine, unless an Eagle specific feature)
- [ ] Add to the changelog_dev.rst file and propose migration text in the pull request

### CODE REVIEW

**Comment by nmerket** [comment]
This is good. With the data_point.zip now gone, I was worried this code would break:

https://github.com/NREL/buildstockbatch/blob/16cf0a867cec151f7021b2c7da06fa28ca403aec/buildstockbatch/base.py#L203-L210

It was looks in data_point.zip and removes things from the directory that are already in there. But if data_point.zip isn't there it skips that block, so I guess it's not hurting anything. I'm not sure what's going on in ComStock so maybe we leave it for now. 

In general, I'd say just go through that cleanup function to make sure it's still relevant with the organization of the files being written with your update.

**Comment by joseph-robertson** [comment]
@nmerket I've updated the residential workflow generator to write argument values for ServerDirectoryCleanup. I'm not sure what else needs to be updated (e.g., pretty sure validation will now fail if `server_directory_cleanup` is found in a project yml file).

**Review by nmerket — COMMENTED** [review]
@joseph-robertson This seems pretty straightforward and I like what you're doing with the server directory cleanup. You're right in that it will throw an error if that argument is there even though you're expecting it. That's easy enough to fix, though. Just add some yaml schema stuff here to tell it what to expect. It's even in the same file.

https://github.com/NREL/buildstockbatch/blob/81b43f0a20efe34ee599e1d0b30f2d32f124768e/buildstockbatch/workflow_generator/residential.py#L43-L54

I haven't tried running it, but it sounds like @munank has and it worked for him, so that's pretty good.

A few things to update:

- [x] The residential workflow generator schema as mentioned above.
- [x] Documentation for the residential workflow generator to document the schema changes.
- [x] Changelog entry

**Comment by joseph-robertson** [comment]
@nmerket Anything else that needs to be done here?

**Comment by asparke2** [comment]
@joseph-robertson I think this is fine as-is and we can fix up the ComStock server directory cleanup as necessary.  One thing to be aware of is that it won't work if `custom_gems = True`.  I don't think you use that for ResStock, so probably not a big deal.  [This branch](https://github.com/NREL/buildstockbatch/tree/feature/enable_os_3x_w_custom_gems) has additional changes to accommodate custom_gems with OS 3.x, but not going to worry about that until FY22.

**Review by nmerket — APPROVED** [review]

**Comment by nmerket** [comment]
Looks good to me. You okay if I merge then?

**Comment by joseph-robertson** [comment]
Let me get review on https://github.com/NREL/resstock/pull/661 and then I'll let you know.

**Pull request merged**
