### PR TITLE
Fixing weather files download on Eagle

### LINKED ISSUE #390: When using default TMY weather URL receiving error-- OSError: [Errno 28] No space left on device
**Describe the bug**
Receiving immediate failure during the sampling step of buildstockbatch when pointing to a URL for weather files.

e.g., `weather_files_url: https://data.nrel.gov/system/files/156/BuildStock_TMY3_FIPS.zip` 

**To Reproduce**
You can reproduce that by using `buildstock-2023.06.0` environment and running national_baseline.yml on Eagle while pointing to the weather file URL.

**Logs**

sampling.out:
```
DEBUG:2023-08-29 08:40:27:buildstockbatch.base:Using OpenStudio version: 3.6.1 with SHA: bb9481519e
DEBUG:2023-08-29 08:40:27:__main__:Output directory = /scratch/pwhite/durham_buildstock_v2
DEBUG:2023-08-29 08:40:27:buildstockbatch.base:Downloading weather files
Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/site-packages/buildstockbatch/base.py", line 115, in _get_weather_files
    f.write(chunk)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/site-packages/buildstockbatch/eagle.py", line 875, in <module>
    main()
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/site-packages/buildstockbatch/utils.py", line 107, in run_with_error_capture
    return func(*args, **kwargs)
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/site-packages/buildstockbatch/eagle.py", line 840, in main
    batch = EagleBatch(args.project_filename)
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/site-packages/buildstockbatch/eagle.py", line 80, in __init__
    weather_dir = self.weather_dir  # noqa E841
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/site-packages/buildstockbatch/eagle.py", line 168, in weather_dir
    self._get_weather_files()
  File "/shared-projects/buildstock/envs/buildstock-2023.06.0/lib/python3.10/site-packages/buildstockbatch/base.py", line 112, in _get_weather_files
    with tempfile.TemporaryFile() as f:
OSError: [Errno 28] No space left on device

real	0m13.196s
user	0m2.673s
sys	0m2.517s

```

**Platform (please complete the following information):**
- Simulation platform: Eagle
- BuildStockBatch version, branch, or sha: buildstock-2023.06.0

### PR DESCRIPTION
**Pull request by nmerket**
Fixes #390.

### CODE REVIEW

**Comment by nmerket** [comment]
@whiphi92 It was the RAM disk thing. I changed it to put the temporary file in the `/tmp/scratch` directory if it exists, which has like 1TB of space. Can you give this a spin and let me know if it works for you? It seems to be working for me.

**Comment by nmerket** [comment]
@whiphi92 is getting the following error, I think in one of the job.out-* files on this one

```
Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/pwhite_weather_tempfile_test/lib/python3.10/site-packages/buildstockbatch/utils.py", line 107, in run_with_error_capture
    return func(*args, **kwargs)
  File "/shared-projects/buildstock/envs/pwhite_weather_tempfile_test/lib/python3.10/site-packages/buildstockbatch/eagle.py", line 830, in main
    batch.run_job_batch(job_array_number)
  File "/shared-projects/buildstock/envs/pwhite_weather_tempfile_test/lib/python3.10/site-packages/buildstockbatch/eagle.py", line 236, in run_job_batch
    self.clear_and_copy_dir(
  File "/shared-projects/buildstock/envs/pwhite_weather_tempfile_test/lib/python3.10/site-packages/buildstockbatch/eagle.py", line 129, in clear_and_copy_dir
    shutil.copytree(src, dst)
  File "/shared-projects/buildstock/envs/pwhite_weather_tempfile_test/lib/python3.10/shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/shared-projects/buildstock/envs/pwhite_weather_tempfile_test/lib/python3.10/shutil.py", line 457, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/shared-projects/buildstock/envs/pwhite_weather_tempfile_test/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/scratch/buildstock/resources/hpxml-measures'
```

So far I have been unable to duplicate it.

**Comment by nmerket** [comment]
I successfully ran a test run last night and it worked for me.

**Review by afontani — APPROVED** [review]
I tried it on Eagle. Everything ran successfully.

**Comment by nmerket** [comment]
It worked for me too. I think we can chalk this up to some Eagle weirdness and go ahead and merge it.

**Pull request merged**
