### PR TITLE
Make it run for resstock.

### PR DESCRIPTION
**Pull request by rajeee**

### CODE REVIEW

**Comment by nmerket** [comment]
@rajeee Is this still relevant?

**Comment by rajeee** [comment]
I think so; unless there is another PR that makes the features/aws_with_custom_gems work for resstock. Either way, things could have changed since this PR so it definitely needs more testing before we can merge.

**Comment by nmerket** [comment]
Yeah, it definitely looks outdated. It's pulling OS 2.9.1 and I think we're using 3.4 at this point. The ComStock team has added a few things in #238 regarding gems. I propose we merge that in first since it's closer to the finish line and then revisit if we bring this one up to date or just start a new branch with changes relevant to the current state of things.

**Comment by afontani** [comment]
@rajeee : Can we close this?

**Comment by asparke2** [comment]
please don't delete this branch yet, I would like to salvage the work

**Pull request merged**
