### PR TITLE
ResStock-HPXML: include_annual arguments

### PR DESCRIPTION
**Pull request by joseph-robertson**
Support the following ReportSimulationOutput changes:
* A bunch of `include_annual_foo` are now available. We will fix (i.e., user has no option to override) requesting all annual outputs, except for system use consumptions which will always not be requested.
* Also fixes new `include_timeseries_system_use_consumptions` argument to always false.

### CODE REVIEW

**Review by nmerket — CHANGES_REQUESTED** [review]
Just pulling up the checklist from the pull request template...

- [x] Code changes (must work)
- [ ] Tests exercising your feature/bug fix (check coverage report on Checks -> BuildStockBatch Tests -> Artifacts) _Is it worth adding a simple test around this feature in the test_workflow_generator.py?_
- [x] Coverage has increased or at least not decreased. Update `minimum_coverage` in `.github/workflows/ci.yml` as necessary.
- [x] All other unit and integration tests passing
- [x] Update validation for project config yaml file changes
- [x] Update existing documentation
- [ ] Run a small batch run on Eagle to make sure it all works if you made changes that will affect Eagle
- [x] Add to the changelog_dev.rst file and propose migration text in the pull request

**Comment by joseph-robertson** [comment]
New `test_workflow_generator.py` checks are commented out because the test checks against resstock develop... but the new arguments aren't on develop yet...

**Review by nmerket — COMMENTED** [review]
I think this is good. At what point do we merge this? Before or after the corresponding resstock change?

**Comment by joseph-robertson** [comment]
I think we merge here, then release buildstockbatch. Then I can go into the resstock PR and point to the tagged buildstockbatch release before merging it into develop. Does that sound right?

**Review by nmerket — APPROVED** [review]

**Pull request merged**
