### PR TITLE
Memory efficient results.csv creation

### LINKED ISSUE #253: Post-processing timeout/memory error for large runs
**Describe the bug**
I have encountered issues post-processing large resstock runs (~1.5MM sims) on Eagle.

Initial error in `postprocessing.out`:
`slurmstepd: error: Detected 1 oom-kill event(s) in step 7788440.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.`

This error was circumvented by requesting bigmem nodes, however, I have timed out running `--postprocessonly`, requiring a large number of bigmem nodes which prevented it from being scheduled in a timely manner.

**To Reproduce**
1. [Project yaml](https://github.com/NREL/resstock/blob/restructure-v3-flex/project_national/flex.yml)
2. Run `--postprocessonly` 
2.1 If requesting bigmem nodes, the job will take a very long time to schedule
2.2 if requesting standard nodes, the out-of-memory error will likely occur

**Logs**
Memory error: `/lustre/eaglefs/projects/scout/flex_measures/flex_full/postprocessing_202110291115.out`
Time out error: `/lustre/eaglefs/projects/scout/flex_measures/flex_full/postprocessing_202111080407.out`

**Platform:**
- Simulation platform: `Eagle`
- BuildStockBatch version, branch, or sha: `restructure-v3-flex` (https://github.com/NREL/buildstockbatch/tree/restructure-v3-flex)
- resstock or comstock repo version, branch, or sha: `restructure-v3-flex` (https://github.com/NREL/resstock/tree/restructure-v3-flex)

### PR DESCRIPTION
**Pull request by rajeee**
Potentially fixes #253.

## Pull Request Description

Instead of loading all the results_jobx.json.gz files at once to memory, use dask to load only the results_jobs for an upgrade at a time. This should prevent out of memory error when dealing with large run with many upgrades.

## Checklist

Not all may apply

- [x] Code changes (must work)
- [x] Tests exercising your feature/bug fix (check coverage report on CircleCI build -> Artifacts)
- [x] All other unit tests passing
- [ ] Update validation for project config yaml file changes
- [ ] Update existing documentation
- [x] Run a small batch run to make sure it all works (local is fine, unless an Eagle specific feature)
- [ ] Add to the changelog_dev.rst file and propose migration text in the pull request

### CODE REVIEW

**Comment by rajeee** [comment]
Works in a small batch. Need to verify for a super large batch that previously would have failed.

**Review by nmerket — APPROVED** [review]
Looks good from what I can see. I think the dask dataframe is a good choice here. Let me know how it goes with a larger dataset.

**Comment by rajeee** [comment]
Works in a large run with 350K buildings, 16 upgrades. With n_worker=10 for postprocessing took ~10 hours.

**Comment by nmerket** [comment]
> Works in a large run with 350K buildings, 16 upgrades. With n_worker=10 for postprocessing took ~10 hours.

That's a long time, but it's good that it worked. I suppose that's what matters.

**Pull request merged**
