### PR TITLE
Fixes temp directory and bigmem issues with kestrel runs

### PR DESCRIPTION
**Pull request by ChristopherCaradonna**
Fixes # .

## Pull Request Description

This fixes Kestrel run errors related the existing files in the common temp directory on local node storage. Eagle assumes there is always local storage, and sets the TMPDIR to /tmp/scratch/$USER. Kestrel always assumes there is no local disk, and sets TMPDIR to /tmp/scratch. Existing files from other users on /tmp/scratch cause buildstock batch to fail.

This fix ensures the temporary directory is set to /tmp/scratch/$USER, avoiding file conflicts.

## Checklist

Not all may apply

- [x] Code changes (must work)
- [x] ~~Tests exercising your feature/bug fix (check coverage report on Checks -> BuildStockBatch Tests -> Artifacts)~~
- [x] Coverage has increased or at least not decreased. Update `minimum_coverage` in `.github/workflows/coverage.yml` as necessary.
- [x] All other unit and integration tests passing
- [x] ~~Update validation for project config yaml file changes~~
- [x] Update existing documentation
- [x] Run a small batch run on Kestrel/Eagle to make sure it all works if you made changes that will affect Kestrel/Eagle
- [ ] Add to the changelog_dev.rst file and propose migration text in the pull request

### CODE REVIEW

**Review by asparke2 — APPROVED** [review]
The real solution may be to get HPC to change the file permissions on /tmp/scratch, but this works in the meantime. @rHorsey suggested doing this via ENV in the kestrel shell scripts because then it doesn't affect Eagle.

**Review by nmerket — COMMENTED** [review]
Looks good to me. Add and entry to the changelog and I'll merge it when you're ready.

**Comment by nmerket** [comment]
Are we feeling like this is ready to merge? I'd like to get this into a release so people can benefit from these bugfixes.

**Comment by asparke2** [comment]
@nmerket yeah, it's good to go, we used it for the Com EUSS runs

**Pull request merged**
