### PR TITLE
Set python version to 3.7.8 

### LINKED ISSUE #194: Issue creating new bsb environment on eagle - ImportError: GLIBCXX_3.4.21
**Describe the bug**
After creating a new environment an error is thrown that reads (in part):
`ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found`

**To Reproduce**
1. Run create_eagle_env.sh on a eagle longin node
2. Run `python -c "import pandas"`

**Expected behavior**
The import to not error

**Solution**
Replace `python=3.7` with `python=3.7.8=hffdb5ce_3_cpython` in https://github.com/NREL/buildstockbatch/blob/develop/create_eagle_env.sh#L29

**Logs**

```
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found
```

**Platform (please complete the following information):**
- Simulation platform: Eagle
- BuildStockBatch version, branch, or sha: https://github.com/NREL/buildstockbatch/commit/451954d48e0c2c749e55a3dcdc1be9a183747f39
- OpenStudio-BuildStock version, branch, or sha: N/A
- Local Desktop OS: N/A

**Additional context**

### PR DESCRIPTION
**Pull request by bonnema**
Fixes #194 
## Pull Request Description
Explicitly set python version to 3.7.8 to play nicer with libraries on Eagle (matches current system python on Eagle)

### CODE REVIEW

**Review by nmerket — CHANGES_REQUESTED** [review]
Fine with me. It looks like CI is failing because ruamel.yaml isn't getting installed correctly even though it is in the setup.py. My guess is it changed names or something. Can you look into that?

**Comment by rHorsey** [comment]
I'm finding ucky issue threads that indicate this is specifically an issue with some miniconda distros.... yay

**Comment by rHorsey** [comment]
I find it depressing that that worked, but hurrah. @nmerket develop is also failing now btw so it'd be good to merge this post-haste.

**Comment by rHorsey** [comment]
Back to the real point - thanks @bonnema for finding a simple doable fix for the eagle anaconda problem!!!

**Review by rHorsey — APPROVED** [review]

**Review by nmerket — APPROVED** [review]

**Pull request merged**
