### PR TITLE
Adding black formatter pre-commit

### PR DESCRIPTION
**Pull request by nmerket**
## Pull Request Description

Adding pre-commit and black code formatter.

## Checklist

Not all may apply

- [ ] Code changes (must work)
- [ ] Tests exercising your feature/bug fix (check coverage report on Checks -> BuildStockBatch Tests -> Artifacts)
- [ ] Coverage has increased or at least not decreased. Update `minimum_coverage` in `.github/workflows/ci.yml` as necessary.
- [ ] All other unit and integration tests passing
- [ ] Update validation for project config yaml file changes
- [ ] Update existing documentation
- [ ] Run a small batch run on Eagle to make sure it all works if you made changes that will affect Eagle
- [ ] Add to the changelog_dev.rst file and propose migration text in the pull request

### CODE REVIEW

**Comment by shorowit** [comment]
Note that as an alternative to developers having to install pre-commit, there are services that will run the pre-commit automatically. Like [this](https://pre-commit.ci) one. It's free and integrates with GitHub.

**Comment by shorowit** [comment]
https://github.com/pre-commit/action even says:

"this action is in maintenance-only mode and will not be accepting new features.

generally you want to use [pre-commit.ci](https://pre-commit.ci/) which is faster and has more features."

**Review by lixiliu — APPROVED** [review]
LGTM. Though you might want to update bsb documentation to show how to activate the pre-commit hook.

**Comment by rajeee** [comment]
Can we keep 120 line length and avoid excessive reformatting of the code base?

**Comment by nmerket** [comment]
@rajee I'm open to it. It looks like to set a custom line length, I'd need to use a [pyproject.toml](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format). However, buildstockbatch is using setup.py. We'll need to convert the setup.py into a pyproject.toml. Would you be able to take a stab at that?

**Comment by rajeee** [comment]
> @rajee I'm open to it. It looks like to set a custom line length, I'd need to use a [pyproject.toml](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format). However, buildstockbatch is using setup.py. We'll need to convert the setup.py into a pyproject.toml. Would you be able to take a stab at that?

Glad you got it sorted without switching the whole project into pyproject.toml. I don't have a good experience with pyproject.toml - I tried using it for buildstock-query but had to revert back to setup.py because at that time, the toml version didn't support editable mode installation.

**Pull request merged**
